added fix for acm console logout
Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

diff --git a/.github/workflows/node-package-dependencies-update.yml b/.github/workflows/node-package-dependencies-update.yml
--- a/.github/workflows/node-package-dependencies-update.yml
+++ b/.github/workflows/node-package-dependencies-update.yml
@@ -2,12 +2,6 @@ name: Update node package dependencies versions
 
 # Set jobs to be configured and executed by schedule.
 on:
-  workflow_dispatch:
-    inputs:
-      environment:
-        required: false
-        description: Environment to run build against
-        type: environment
   push:
     branches:
       - 'main'
@@ -72,20 +66,33 @@ jobs:
           echo "Preparing to install the updated package dependencies"
           npm install
 
+      - name: Checking for unused packages dependencies listed within package.json
+        continue-on-error: true
+        id: unused
+        run: |
+          echo "Preparing to check for unused packages dependencies within the project"
+          npx depcheck
+
       - name: Verify node package dependencies updated to latest versions (failure)
         id: verify-failure
         if: steps.reinstall.outcome == 'failure'
         run: |
-          echo -e "#### Failed to update the outdated node package dependencies successfully. Manual update and install needed.\n---" >> .github/logs/update-log-$(date +%m-%d-%y).md
+          echo -e "\n#### Failed to update the outdated node package dependencies successfully. Manual update and install needed.\n---" >> .github/logs/update-log-$(date +%m-%d-%y).md
 
       - name: Verify node modules dependencies updated to latest versions (succecss)
         id: verify-success
         if: steps.reinstall.outcome == 'success'
         run: |
-          echo -e "#### Successfully updated the node modules dependencies.\n---" >> .github/logs/update-log-$(date +%m-%d-%y).md
+          echo -e "\n#### Successfully updated the node modules dependencies.\n---" >> .github/logs/update-log-$(date +%m-%d-%y).md
 
-      - name: Resolve node modules package vulnerabilities
+      - name: Verify modules with security vulnerabilities
         id: audit
+        continue-on-error: true # Continuing on error. The initial command will return an exit 1 code; however, this is okay.
+        run: |
+          npm audit
+
+      - name: Resolve node modules security vulnerabilities
+        id: audit-fix
         continue-on-error: true # Continuing on error. This step is to avoid vulnerabilities; however, we incase it fails we will need to resolve them manually.
         run: |
           echo "Preparing to address security vulnerabilities in the updated package dependencies."
@@ -98,7 +105,7 @@ jobs:
           git status
 
       - name: Create pull request for updated node modules versions
-        if: steps.outdated.outcome == 'failure'
+        if: steps.updated.outcome == 'failure'
         uses: peter-evans/create-pull-request@v3
         with:
           add-paths: .
